# ClearItems by l1ratch. A plugin that removes all lying objects in the worlds after a specified interval.
# Примечание: Если вы хотите отключить определенное оповещение оставьте строку пустой: notification: ""

# Интервал удаления предметов в тиках (1 секунда = 20 тиков)
clearInterval: 300

# Сообщение о удалении предмета
removalMessage: "&cItem removed!"

# Сообщение об оставшемся времении до удаления
warningMessages:
  - "15,Item will be removed in 15 seconds!"
  - "5,Item will be removed in 5 seconds!"


#Minecraft has a variety of colors that can be used to highlight text or objects. Here are some of them:
#  1.Черный (BLACK)
#  2.Темно-синий (DARK_BLUE)
#  3.Темно-зеленый (DARK_GREEN)
#  4.Темно-бирюзовый (DARK_AQUA)
#  5.Темно-красный (DARK_RED)
#  6.Темно-фиолетовый (DARK_PURPLE)
#  7.Золотой (GOLD)
#  8.Серый (GRAY)
#  9.Темно-серый (DARK_GRAY)
#  10.Синий (BLUE)
#  11.Зеленый (GREEN)
#  12.Бирюзовый (AQUA)
#  13.Красный (RED)
#  14.Фиолетовый (LIGHT_PURPLE)
#  15.Желтый (YELLOW)
#  16.Белый (WHITE)