# ClearItems by l1ratch. A plugin that removes all lying objects in the worlds after a specified interval.
# Note: If you want to disable a specific alert, leave the line blank: notification: ""

# The interval in seconds before cleaning the items.
clearInterval: 60

# A message about the removal of items.
clearMessage: "&cClearItems &7&l| &aВсе предметы были удалены."

# A message about the remaining time before deletion.
warningMessages:
  - "15,&cClearItems &7&l| &eItem will be removed in 15 seconds!"
  - "5,&cClearItems &7&l| &eItem will be removed in 5 seconds!"
